### ISSUE TITLE
Inconsistent font loading on Chrome

### ISSUE THREAD

**Issue by richardatval** [aylestoneallotments/website#3]
Looks like this might be the case of a protocol mismatch.

http://blog.dbain.com/2012/12/google-web-fonts-not-showing-in-google.html

**Comment by aylestoneallotments** [comment]
Attempted to fix with with webkit animation that causes reload: https://code.google.com/p/chromium/issues/detail?id=336476

**Comment by aylestoneallotments** [comment]
Google web font loader seems to fix the problem

**Comment by aylestoneallotments** [comment]
Still got problems with one button. My solution was to not provide a fallback for that particular instance: 

`input[type="submit"] {
        font: 700 1em "Bitter";
        background: #fff;
        color: $brand-primary;
    }`

That seemed to do the trick
